language: php

php:
  - 7.1

env:
  - APP_ENV=travis

services:
  - elasticsearch
  - mysql

before_script:
  - sleep 10
  - cd ./src
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'create database brisklypapers_testing;'
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch mapper-attachments
  - sudo service elasticsearch restart

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - travis_retry php vendor/bin/coveralls --coverage_clover=coverage.xml