language: php

php:
  - 7.1

script: src/vendor/bin/phpunit --coverage-clover=coverage.xml

services:
  - elasticsearch
  - mysql

before_script:
  - sleep 10
  - cd ./src
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'create database homestead_test;'

env:
  - APP_ENV=travis